buffer_size : 100000
batch_size : 3000
max_steps: 50000
simulation_freq: 5
gamma : 0.99
epsilon : 1.0
epsilon_min : 0.01
epsilon_decay : 0.97
train_epochs : 10

env:
    render_mode : rgb_array
    screen_width : 200
    screen_height : 200
    block_size : 20
    max_hunger_coef : 1
    max_steps_coef: 30
actor_config: 
    lr: 0.0001
    loss: MSE
    layer1: 128
    layer2: 128
    gamma: 0.99